In [1]:
import polygon_ECT as poly
from shape_reader import ShapeReader

/home/hklahti/Documents/ect/code/repo/ECTOPLASM/polygon_ECT.py:300: SyntaxWarning: invalid escape sequence '\i'
  '''


In [2]:
# Read in shapes
s1=ShapeReader.shape_from_file('data/irregular_octahedron2.off',prepare=True)
s2=ShapeReader.shape_from_file('data/irregular_octahedron.off',prepare=True)

In [3]:
ECT1=poly.return_ECT(s1) #Compute the proto-transforms
ECT2=poly.return_ECT(s2)

In [4]:
d11=poly.ECT_distance_s(ECT1) # The self-inner product
d22=poly.ECT_distance_s(ECT2) 
d12=poly.ECT_distance_d(ECT1,ECT2) # The cross term

In [5]:
d11+d22-2*d12 # Squared distance

array([5.641969])

In [24]:
from numpy import genfromtxt
import numpy as np
dirs = genfromtxt('directions326.csv', delimiter=',')
n=1000
heights=np.linspace(-1,1,n)
def ECT_matrix(shape,directions,heights):
    n=len(heights)
    m=len(dirs)
    matrix=np.zeros([n,m])
    for i in range(n):
        for j in range(m):
            matrix[i,j]=shape.compute_discrete_ECT(directions[j],heights[i])
    return(matrix)

In [25]:
s1.prepare_for_discrete_ECT()
s2.prepare_for_discrete_ECT()
ect1=ECT_matrix(s1,dirs,heights)
ect2=ECT_matrix(s2,dirs,heights)

In [26]:
np.sum((ect1-ect2)**2)/(n*len(dirs))*math.pi*8 # Squared distance

5.722555570323022

In [27]:
d11

array([38.74989464])

In [29]:
np.sum(ect1**2)/(n*len(dirs))*math.pi*8

38.70519243520872

In [30]:
d22

array([38.74989466])

In [31]:
np.sum(ect2**2)/(n*len(dirs))*math.pi*8

38.70519243520872